export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const SET_LOGIN_USER = 'SET_LOGIN_USER';

export const SET_ADMIN_MODE = 'SET_ADMIN_MODE';
export const SET_APP_NOTIFICATION = 'SET_APP_NOTIFICATION';

export const SET_CURRENT_ORGANIZATION = 'SET_CURRENT_ORGANIZATION';
export const SET_COLLABORATED_ORGANIZATIONS = 'SET_COLLABORATED_ORGANIZATIONS';
export const SET_OWNED_ORGANIZATIONS = 'SET_OWNED_ORGANIZATIONS';
export const SET_ORGANIZATIONS_AVATARS = 'SET_ORGANIZATIONS_AVATARS';

export const SET_ORGANIZATION_COLLABORATORS = 'SET_ORGANIZATION_COLLABORATORS';
export const SET_ORGANIZATION_OWNER = 'SET_ORGANIZATION_OWNER';
export const SET_ORGANIZATION_PAGE = 'SET_ORGANIZATION_PAGE';
export const SET_ORGANIZATION_PROJECTS = 'SET_ORGANIZATION_PROJECTS';
export const SET_ORGANIZATION_AVATAR = 'SET_ORGANIZATION_AVATAR';
export const SET_ORGANIZATION_BACKGROUND = 'SET_ORGANIZATION_BACKGROUND';

export const SET_ORGANIZATION_EXTERNAL_LINK_URL = 'SET_ORGANIZATION_EXTERNAL_LINK_URL';
export const SET_ORGANIZATION_EXTERNAL_LINK_LABEL = 'SET_ORGANIZATION_EXTERNAL_LINK_LABEL';
export const SET_ORGANIZATION_SOCIAL_LINK_PATH = 'SET_ORGANIZATION_SOCIAL_LINK_PATH';
export const SET_ORGANIZATION_SOCIAL_ORDER = 'SET_ORGANIZATION_SOCIAL_ORDER';
export const SET_ORGANIZATION_URLS = 'SET_ORGANIZATION_URLS';
